version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build 
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "testing"
      - run: npm test
  hiThere:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "hellloooo"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hiThere
      - test:
        requires:
          -hiThere